# Generated by Django 5.2.3 on 2025-06-16 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.IntegerField()),
                ("name_english", models.CharField(max_length=10)),
                ("name_in_japanese", models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("member_code", models.CharField(max_length=12)),
                ("active", models.BooleanField()),
                ("active_status_change_history", models.TextField()),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("middle_name", models.CharField(blank=True, max_length=50, null=True)),
                ("known_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "name_in_japanese",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("name_change_history", models.TextField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("U", "Unknown"),
                            ("M", "Male"),
                            ("F", "Female"),
                            ("O", "Other"),
                        ],
                        default="U",
                        max_length=2,
                    ),
                ),
                (
                    "gender_for_inf_cert",
                    models.CharField(
                        choices=[
                            ("U", "Unknown"),
                            ("M", "Male"),
                            ("F", "Female"),
                            ("O", "Other"),
                        ],
                        default="U",
                        max_length=2,
                    ),
                ),
                ("gender_change_history", models.TextField(blank=True, null=True)),
                ("sso_email", models.EmailField(max_length=254)),
                ("contact_email", models.EmailField(max_length=254)),
                ("last_cnf_cert_number", models.IntegerField()),
                ("last_other_cert_number", models.IntegerField()),
                ("last_inf_cert_number", models.IntegerField()),
                ("date_of_birth", models.DateField()),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=30)),
                ("province", models.CharField(max_length=20)),
                ("postal_code", models.CharField(max_length=20)),
                ("phone_1", models.CharField(blank=True, max_length=20, null=True)),
                ("phone_2", models.CharField(blank=True, max_length=20, null=True)),
                ("phone_3", models.CharField(blank=True, max_length=20, null=True)),
                ("date_of_first_registration", models.DateField(blank=True, null=True)),
                ("date_of_last_registration", models.DateField(blank=True, null=True)),
                ("date_of_first_grading", models.DateField(blank=True, null=True)),
                ("date_of_last_grading", models.DateField(blank=True, null=True)),
                ("board_of_directors", models.BooleanField()),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("created_by", models.IntegerField()),
                ("edited_at", models.DateTimeField()),
                ("edited_by", models.IntegerField()),
                (
                    "dojo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="membership_management.dojo",
                    ),
                ),
                (
                    "current_rank",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="membership_management.rank",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DojoLeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("created_at", models.DateTimeField()),
                ("created_by", models.CharField(max_length=255)),
                ("edited_at", models.DateTimeField()),
                ("edited_by", models.CharField(max_length=255)),
                (
                    "dojo_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="membership_management.dojo",
                    ),
                ),
                (
                    "member_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="membership_management.member",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Grading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(max_length=50)),
                ("grading_data", models.DateTimeField()),
                ("location", models.TextField()),
                ("city", models.CharField(max_length=30)),
                ("province", models.CharField(max_length=20)),
                ("head_examiner_name", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField()),
                ("created_by", models.CharField(max_length=255)),
                ("edited_at", models.DateTimeField()),
                ("edited_by", models.CharField(max_length=255)),
                (
                    "head_examiner_member",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="head_examiner",
                        to="membership_management.member",
                    ),
                ),
                (
                    "second_examiner_member",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="second_examiner",
                        to="membership_management.member",
                    ),
                ),
                (
                    "third_examiner_member",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="third_examiner",
                        to="membership_management.member",
                    ),
                ),
                (
                    "head_examiner_rank",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="head_examiner_rank",
                        to="membership_management.rank",
                    ),
                ),
                (
                    "second_examiner_rank",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="second_examiner_rank",
                        to="membership_management.rank",
                    ),
                ),
                (
                    "third_examiner_rank",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="third_examiner_rank",
                        to="membership_management.rank",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sso_id", models.IntegerField()),
                ("role", models.IntegerField()),
                (
                    "member_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="membership_management.member",
                    ),
                ),
            ],
        ),
    ]
