# Generated by Django 5.2.3 on 2025-06-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership_management", "0002_rank_member_dojoleader_grading_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="dojoleader",
            name="active",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
