# Generated by Django 5.2.3 on 2025-06-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership_management", "0003_dojoleader_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dojoleader",
            old_name="dojo_id",
            new_name="dojo",
        ),
        migrations.RenameField(
            model_name="dojoleader",
            old_name="member_id",
            new_name="member",
        ),
        migrations.RemoveField(
            model_name="member",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="member",
            name="gender_for_inf_cert",
        ),
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.AlterField(
            model_name="member",
            name="known_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="member",
            name="name_in_japanese",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
