# Generated by Django 5.2.3 on 2025-06-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership_management", "0004_rename_dojo_id_dojoleader_dojo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="gender",
            field=models.IntegerField(
                choices=[(0, "Unknown"), (1, "Male"), (2, "Female"), (3, "Other")],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="gender_for_inf_cert",
            field=models.IntegerField(
                choices=[(0, "Unknown"), (1, "Male"), (2, "Female")], default=0
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.IntegerField(
                choices=[
                    (0, "Guest"),
                    (1, "Member"),
                    (2, "Leader"),
                    (3, "Officer"),
                    (4, "Admin"),
                ],
                default=0,
            ),
        ),
    ]
