# Generated by Django 5.2.3 on 2025-06-17 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "membership_management",
            "0005_member_gender_member_gender_for_inf_cert_user_role",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="member_id",
            new_name="member",
        ),
        migrations.RemoveField(
            model_name="grading",
            name="date",
        ),
        migrations.RemoveField(
            model_name="member",
            name="date_of_last_grading",
        ),
        migrations.RemoveField(
            model_name="rank",
            name="name_english",
        ),
        migrations.AddField(
            model_name="grading",
            name="fees_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="grading",
            name="notes",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="grading",
            name="notes_for_member",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="grading",
            name="reciept_number",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="grading",
            name="second_examiner_name",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="grading",
            name="third_examiner_name",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="member",
            name="officers",
            field=models.IntegerField(
                choices=[
                    (0, "Regular Member"),
                    (1, "President"),
                    (2, "Vice President"),
                    (3, "Executive Secretary"),
                    (4, "Membership Secretary"),
                    (5, "Treasurer"),
                    (6, "Community"),
                    (10, "Others"),
                ],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="rank",
            name="name_in_english",
            field=models.IntegerField(
                choices=[
                    (0, "No Rank"),
                    (1, "6 Kyu"),
                    (2, "5 Kyu"),
                    (3, "4 Kyu"),
                    (4, "3 Kyu"),
                    (5, "2 Kyu"),
                    (6, "1 Kyu"),
                    (7, "1 Dan"),
                    (8, "2 Dan"),
                    (9, "3 Dan"),
                    (10, "4 Dan"),
                    (11, "5 Dan"),
                    (12, "Renshi"),
                    (13, "Kyoshi"),
                    (14, "Hanshi"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="dojo",
            name="created_by",
            field=models.ForeignKey(
                db_column="created_by",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="membership_management.user",
            ),
        ),
        migrations.AlterField(
            model_name="dojo",
            name="edited_by",
            field=models.ForeignKey(
                db_column="edited_by",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="membership_management.user",
            ),
        ),
        migrations.AlterField(
            model_name="dojoleader",
            name="created_by",
            field=models.ForeignKey(
                db_column="created_by",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="membership_management.user",
            ),
        ),
        migrations.AlterField(
            model_name="dojoleader",
            name="edited_by",
            field=models.ForeignKey(
                db_column="edited_by",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="membership_management.user",
            ),
        ),
        migrations.AlterField(
            model_name="dojoleader",
            name="end_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="dojoleader",
            name="start_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="grading",
            name="created_by",
            field=models.ForeignKey(
                db_column="created_by",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="membership_management.user",
            ),
        ),
        migrations.AlterField(
            model_name="grading",
            name="edited_by",
            field=models.ForeignKey(
                db_column="edited_by",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="membership_management.user",
            ),
        ),
        migrations.AlterField(
            model_name="grading",
            name="head_examiner_member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="membership_management.member",
            ),
        ),
        migrations.AlterField(
            model_name="grading",
            name="head_examiner_rank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="membership_management.rank",
            ),
        ),
        migrations.AlterField(
            model_name="grading",
            name="location",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="grading",
            name="second_examiner_member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="membership_management.member",
            ),
        ),
        migrations.AlterField(
            model_name="grading",
            name="second_examiner_rank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="membership_management.rank",
            ),
        ),
        migrations.AlterField(
            model_name="grading",
            name="third_examiner_member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="membership_management.member",
            ),
        ),
        migrations.AlterField(
            model_name="grading",
            name="third_examiner_rank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="membership_management.rank",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="created_by",
            field=models.ForeignKey(
                db_column="created_by",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="membership_management.user",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="edited_by",
            field=models.ForeignKey(
                db_column="edited_by",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="membership_management.user",
            ),
        ),
        migrations.AlterField(
            model_name="rank",
            name="name_in_japanese",
            field=models.IntegerField(
                choices=[
                    (0, "無級"),
                    (1, "六級"),
                    (2, "五級"),
                    (3, "四級"),
                    (4, "三級"),
                    (5, "二級"),
                    (6, "一級"),
                    (7, "初段"),
                    (8, "二段"),
                    (9, "三段"),
                    (10, "四段"),
                    (11, "五段"),
                    (12, "錬士"),
                    (13, "教士"),
                    (14, "範士"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="rank",
            name="rank",
            field=models.IntegerField(
                choices=[(1, "Kyu"), (2, "Dan"), (3, "Shogo")], default=1
            ),
        ),
        migrations.CreateModel(
            name="GradingResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cnf_cert_number", models.IntegerField()),
                ("other_cert_number", models.IntegerField()),
                ("other_cert_region", models.CharField(max_length=20)),
                ("inf_cert_number", models.IntegerField()),
                ("fees_paid", models.DecimalField(decimal_places=2, max_digits=3)),
                ("receipt_number", models.CharField(max_length=20)),
                (
                    "printed",
                    models.IntegerField(
                        choices=[
                            (0, "Not Applicable"),
                            (1, "Not ready"),
                            (2, "Ready to print"),
                            (3, "printed"),
                            (4, "Given to dojo leader or regional leader"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "printed_language",
                    models.IntegerField(
                        choices=[
                            (0, "Unknown"),
                            (1, "English"),
                            (2, "French"),
                            (3, "Japanese"),
                            (4, "Other"),
                        ],
                        default=0,
                    ),
                ),
                ("notes_user", models.TextField()),
                ("notes", models.TextField()),
                ("created_at", models.DateTimeField()),
                ("edited_at", models.DateTimeField()),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="membership_management.user",
                    ),
                ),
                (
                    "dojo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="membership_management.dojo",
                    ),
                ),
                (
                    "dojo_leader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="membership_management.member",
                    ),
                ),
                (
                    "edited_by",
                    models.ForeignKey(
                        db_column="edited_by",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="membership_management.user",
                    ),
                ),
                (
                    "given_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="membership_management.member",
                    ),
                ),
                (
                    "grading",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="membership_management.grading",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="membership_management.member",
                    ),
                ),
                (
                    "rank_granted",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="membership_management.rank",
                    ),
                ),
                (
                    "rank_requested",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="membership_management.rank",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_date", models.DateField()),
                (
                    "registration_type",
                    models.IntegerField(
                        choices=[(0, "Invalid"), (1, "New"), (2, "Renew")], default=0
                    ),
                ),
                ("fees_paid", models.DecimalField(decimal_places=2, max_digits=3)),
                ("reciept_number", models.CharField(max_length=20)),
                ("notes_for_member", models.TextField()),
                ("notes", models.TextField()),
                ("created_at", models.DateTimeField()),
                ("edited_at", models.DateTimeField()),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="membership_management.user",
                    ),
                ),
                (
                    "dojo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="membership_management.dojo",
                    ),
                ),
                (
                    "dojo_leader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="membership_management.member",
                    ),
                ),
                (
                    "edited_by",
                    models.ForeignKey(
                        db_column="edited_by",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="membership_management.user",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="membership_management.member",
                    ),
                ),
            ],
        ),
    ]
