# Generated by Django 5.2.4 on 2025-07-06 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "membership_management",
            "0006_rename_member_id_user_member_remove_grading_date_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="grading",
            name="head_examiner_rank",
            field=models.IntegerField(
                choices=[
                    (0, "No Rank"),
                    (1, "6 Kyu"),
                    (2, "5 Kyu"),
                    (3, "4 Kyu"),
                    (4, "3 Kyu"),
                    (5, "2 Kyu"),
                    (6, "1 Kyu"),
                    (7, "1 Dan"),
                    (8, "2 Dan"),
                    (9, "3 Dan"),
                    (10, "4 Dan"),
                    (11, "5 Dan"),
                    (12, "Renshi"),
                    (13, "Kyoshi"),
                    (14, "Hanshi"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="current_rank",
            field=models.IntegerField(
                choices=[
                    (0, "No Rank"),
                    (1, "6 Kyu"),
                    (2, "5 Kyu"),
                    (3, "4 Kyu"),
                    (4, "3 Kyu"),
                    (5, "2 Kyu"),
                    (6, "1 Kyu"),
                    (7, "1 Dan"),
                    (8, "2 Dan"),
                    (9, "3 Dan"),
                    (10, "4 Dan"),
                    (11, "5 Dan"),
                    (12, "Renshi"),
                    (13, "Kyoshi"),
                    (14, "Hanshi"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="grading",
            name="third_examiner_rank",
            field=models.IntegerField(
                choices=[
                    (0, "No Rank"),
                    (1, "6 Kyu"),
                    (2, "5 Kyu"),
                    (3, "4 Kyu"),
                    (4, "3 Kyu"),
                    (5, "2 Kyu"),
                    (6, "1 Kyu"),
                    (7, "1 Dan"),
                    (8, "2 Dan"),
                    (9, "3 Dan"),
                    (10, "4 Dan"),
                    (11, "5 Dan"),
                    (12, "Renshi"),
                    (13, "Kyoshi"),
                    (14, "Hanshi"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="gradingresult",
            name="rank_requested",
            field=models.IntegerField(
                choices=[
                    (0, "No Rank"),
                    (1, "6 Kyu"),
                    (2, "5 Kyu"),
                    (3, "4 Kyu"),
                    (4, "3 Kyu"),
                    (5, "2 Kyu"),
                    (6, "1 Kyu"),
                    (7, "1 Dan"),
                    (8, "2 Dan"),
                    (9, "3 Dan"),
                    (10, "4 Dan"),
                    (11, "5 Dan"),
                    (12, "Renshi"),
                    (13, "Kyoshi"),
                    (14, "Hanshi"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="gradingresult",
            name="rank_granted",
            field=models.IntegerField(
                choices=[
                    (0, "No Rank"),
                    (1, "6 Kyu"),
                    (2, "5 Kyu"),
                    (3, "4 Kyu"),
                    (4, "3 Kyu"),
                    (5, "2 Kyu"),
                    (6, "1 Kyu"),
                    (7, "1 Dan"),
                    (8, "2 Dan"),
                    (9, "3 Dan"),
                    (10, "4 Dan"),
                    (11, "5 Dan"),
                    (12, "Renshi"),
                    (13, "Kyoshi"),
                    (14, "Hanshi"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="grading",
            name="second_examiner_rank",
            field=models.IntegerField(
                choices=[
                    (0, "No Rank"),
                    (1, "6 Kyu"),
                    (2, "5 Kyu"),
                    (3, "4 Kyu"),
                    (4, "3 Kyu"),
                    (5, "2 Kyu"),
                    (6, "1 Kyu"),
                    (7, "1 Dan"),
                    (8, "2 Dan"),
                    (9, "3 Dan"),
                    (10, "4 Dan"),
                    (11, "5 Dan"),
                    (12, "Renshi"),
                    (13, "Kyoshi"),
                    (14, "Hanshi"),
                ],
                default=0,
            ),
        ),
        migrations.RemoveField(
            model_name="user",
            name="member",
        ),
        migrations.AlterField(
            model_name="dojo",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="grading",
            name="edited_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="edited_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="grading",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="gradingresult",
            name="edited_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dojoleader",
            name="edited_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dojo",
            name="edited_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="gradingresult",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="edited_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dojoleader",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Rank",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
