# Generated by Django 5.2.4 on 2025-07-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership_management", "0007_alter_grading_head_examiner_rank_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dojo",
            name="probation",
            field=models.IntegerField(
                choices=[
                    (0, "No"),
                    (1, "Yes"),
                    (2, "Did not apply officially"),
                    (3, "Denied"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="dojo",
            name="province",
            field=models.CharField(
                choices=[
                    ("AB", "Alberta"),
                    ("BC", "British Columbia"),
                    ("MB", "Manitoba"),
                    ("NB", "New Brunswick"),
                    ("NL", "Newfoundland and Labrador"),
                    ("NS", "Nova Scotia"),
                    ("ON", "Ontario"),
                    ("PE", "Prince Edward Island"),
                    ("QC", "Quebec"),
                    ("SK", "Saskatchewan"),
                    ("NT", "Northwest Territories"),
                    ("NU", "Nunavut"),
                    ("YT", "Yukon"),
                ],
                default="AB",
                max_length=20,
            ),
        ),
    ]
